version: '3.8'

services:
  db:
    container_name: reddit_clone_postgres
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - reddit_clone_network

volumes:
  postgres:

networks:
  reddit_clone_network:
    driver: bridge
